### ISSUE TITLE
Unable to upload a jfr file reading

### ISSUE THREAD

**Issue by saurabh7248** [kornilova-l/flamegraph-visualizer#27]
While uploading a jfr file reading a pop up comes up and says file was not sent.

**Comment by kornilova-l** [comment]
@saurabh7248, Thanks for creating the issue! Could you please specify what os do you use?

**Comment by raiju** [comment]
I get a similar error w/ IntelliJ 2019.2.4 w/ version 0.8.1 of the IntelliJ plugin. The `upload-file` call 404s (as a side-note, it's a bit surprising that the code in the browser doesn't seem to completely match the code in this repo...). When I check `~/Library/Caches/IntelliJIdea2019.2/flamegraph-profiler/log/uploaded-files/not-converted`, it contains two files: `recording.jfr` & `temp-1574285962748` (it's a small file, so fits in a single upload file in the logic).

I tried tracing the code, but think I got a bit lost as to how the file is supposed to get converted.

**Comment by atennapel** [comment]
I'm also unable to upload a JFR file (generated using Zulu Mission Control), in Chrome on Windows 10.

**Comment by walles** [comment]
I'm getting this with Firefox 73.0.1 on macOS 10.15.3 Catalina.

**Comment by jshook** [comment]
Same issue on 2022.2.3 in chrome

**Comment by Farkhondeh-Arzi** [comment]
same issue. and the error shown in intellij Idea:
java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "stacks" is null
	at com.github.kornilova203.flameviewer.converters.cflamegraph.JfrToStacksConverter.removePackageInParameters(JfrToStacksConverter.java:34)
	at com.github.kornilova203.flameviewer.converters.cflamegraph.JfrToStacksConverter.convert(JfrToStacksConverter.java:24)
	at com.github.kornilova203.flameviewer.converters.cflamegraph.JfrConvertersComposition.convert(JfrConvertersComposition.java:57)
	at com.github.kornilova203.flameviewer.converters.cflamegraph.JfrConvertersComposition.convert(JfrConvertersComposition.java:37)
	at com.github.kornilova203.flameviewer.converters.cflamegraph.CFlamegraphFileSaver.tryToConvert(CFlamegraphFileSaver.kt:19)
	at com.github.kornilova203.flameviewer.server.FileUploader.tryToConvertFileToAnotherFile(FileUploader.kt:47)
	at com.github.kornilova203.flameviewer.server.FileUploader.upload(FileUploader.kt:29)
	at com.github.kornilova203.flameviewer.server.handlers.FileHandler.processPost(FileHandler.kt:26)
	at com.github.kornilova203.flameviewer.server.RequestHandlerBase.process(RequestHandlerBase.kt:15)
	at com.github.kornilova203.flameviewer.server.handlers.DelegatingRequestHandler.process(DelegatingRequestHandler.kt:16)
	at com.github.kornilova203.flameviewer.server.IntellijRequestHandler.process(IntellijRequestHandler.kt:56)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process$checkAndProcess(DelegatingHttpRequestHandler.kt:21)
	at org.jetbrains.io.DelegatingHttpRequestHandler.access$process$checkAndProcess(DelegatingHttpRequestHandler.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:35)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:34)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process$lambda$0(DelegatingHttpRequestHandler.kt:34)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.lambda$findFirstSafe$0(ExtensionProcessingHelper.java:47)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:57)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe(ExtensionProcessingHelper.java:47)
	at com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.java:50)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:34)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:11)
	at org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:21)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
