### ISSUE TITLE
When I click to Tools>Flamegraph Profiler>Upload File Browser opened just with 404 not found message. 

### ISSUE THREAD

**Issue by KyongSik-Yoon** [kornilova-l/flamegraph-visualizer#5]
@kornilova-l  The url form is like below.
http://localhost:63342/flamegraph-profiler/outgoing-calls?project=uploaded-files

I already profiling using Run with Flamegraph profiler. And also I checked ser file generated normally.
After finish profiling I wanted saw Flamegraph so I clicked Upload File menu.
But I just could saw 404 Not Found message with IntelliJ IDEA 2017.3.3 message under line.

**Comment by kornilova-l** [comment]
@KyongSik-Yoon does it work if you click **Tools | Flamegraph Profiler | Open Results...**?
It also would be really helpful if you attach a log file. You can find it here: **Help | Show log in file manager**, you should find there `idea.log` file

**Comment by KyongSik-Yoon** [comment]
@kornilova-l Open Results also not working. I attached idea.log
2018-01-30 17:15:37,632 [  26928]   INFO - .openapi.util.LowMemoryWatcher - Low memory signal received. 
2018-01-30 17:15:39,655 [  28951]   INFO - pl.ProjectRootManagerComponent - project roots have changed 
2018-01-30 17:15:39,865 [  29161]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 150ms; general responsiveness: ok; EDT responsiveness: ok 
2018-01-30 17:15:39,950 [  29246]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 84ms; general responsiveness: ok; EDT responsiveness: ok 
2018-01-30 17:15:39,990 [  29286]   INFO - g.FileBasedIndexProjectHandler - Reindexing refreshed files: 0 to update, calculated in 3ms 
2018-01-30 17:16:55,394 [ 104690]   INFO - krasa.visualvm.VisualVMContext - saving context: VisualVMContext{appId=22852157513435} 
2018-01-30 17:16:58,727 [ 108023]   INFO - .script.IdeScriptEngineManager - javax.script.ScriptEngineManager initialized in 1026 ms 
2018-01-30 17:17:12,587 [ 121883]   INFO - g.FileBasedIndexProjectHandler - Reindexing refreshed files: 1 to update, calculated in 3ms 
2018-01-30 17:17:13,056 [ 122352]   INFO - .diagnostic.PerformanceWatcher - Reindexing refreshed files took 469ms; general responsiveness: ok; EDT responsiveness: ok 
2018-01-30 17:17:27,068 [ 136364]  ERROR - org.jetbrains.io.BuiltInServer - null 
java.lang.NullPointerException
	at io.netty.buffer.Unpooled.wrappedBuffer(Unpooled.java:154)
	at com.github.kornilova_l.flamegraph.plugin.server.ProfilerHttpRequestHandler.sendBytes(ProfilerHttpRequestHandler.java:59)
	at com.github.kornilova_l.flamegraph.plugin.server.ProfilerHttpRequestHandler.processHtmlRequest(ProfilerHttpRequestHandler.java:356)
	at com.github.kornilova_l.flamegraph.plugin.server.ProfilerHttpRequestHandler.processGetMethod(ProfilerHttpRequestHandler.java:316)
	at com.github.kornilova_l.flamegraph.plugin.server.ProfilerHttpRequestHandler.process(ProfilerHttpRequestHandler.java:261)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:42)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:57)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:29)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:25)
	at org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:20)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:72)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
2018-01-30 17:17:27,069 [ 136365]  ERROR - org.jetbrains.io.BuiltInServer - IntelliJ IDEA 2017.3.3  Build #IU-173.4301.25 
2018-01-30 17:17:27,069 [ 136365]  ERROR - org.jetbrains.io.BuiltInServer - JDK: 1.8.0_152-release 
2018-01-30 17:17:27,069 [ 136365]  ERROR - org.jetbrains.io.BuiltInServer - VM: OpenJDK 64-Bit Server VM 
2018-01-30 17:17:27,069 [ 136365]  ERROR - org.jetbrains.io.BuiltInServer - Vendor: JetBrains s.r.o 
2018-01-30 17:17:27,070 [ 136366]  ERROR - org.jetbrains.io.BuiltInServer - OS: Mac OS X 
2018-01-30 17:17:27,070 [ 136366]  ERROR - org.jetbrains.io.BuiltInServer - Last Action: java-profiling-plugin.server 
2018-01-30 17:17:28,494 [ 137790]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 2018. 1. 30. 오전 11:25) 
2018-01-30 17:17:34,679 [ 143975]  ERROR - org.jetbrains.io.BuiltInServer - null 
java.lang.NullPointerException
	at io.netty.buffer.Unpooled.wrappedBuffer(Unpooled.java:154)
	at com.github.kornilova_l.flamegraph.plugin.server.ProfilerHttpRequestHandler.sendBytes(ProfilerHttpRequestHandler.java:59)
	at com.github.kornilova_l.flamegraph.plugin.server.ProfilerHttpRequestHandler.processHtmlRequest(ProfilerHttpRequestHandler.java:356)
	at com.github.kornilova_l.flamegraph.plugin.server.ProfilerHttpRequestHandler.processGetMethod(ProfilerHttpRequestHandler.java:316)
	at com.github.kornilova_l.flamegraph.plugin.server.ProfilerHttpRequestHandler.process(ProfilerHttpRequestHandler.java:261)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:42)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:57)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:29)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:25)
	at org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:20)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:72)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
2018-01-30 17:17:34,681 [ 143977]  ERROR - org.jetbrains.io.BuiltInServer - IntelliJ IDEA 2017.3.3  Build #IU-173.4301.25 
2018-01-30 17:17:34,682 [ 143978]  ERROR - org.jetbrains.io.BuiltInServer - JDK: 1.8.0_152-release 
2018-01-30 17:17:34,682 [ 143978]  ERROR - org.jetbrains.io.BuiltInServer - VM: OpenJDK 64-Bit Server VM 
2018-01-30 17:17:34,682 [ 143978]  ERROR - org.jetbrains.io.BuiltInServer - Vendor: JetBrains s.r.o 
2018-01-30 17:17:34,682 [ 143978]  ERROR - org.jetbrains.io.BuiltInServer - OS: Mac OS X 
2018-01-30 17:17:34,682 [ 143978]  ERROR - org.jetbrains.io.BuiltInServer - Last Action: flamegraph-profiler.ShowUploadFilePageAction 
2018-01-30 17:18:08,459 [ 177755]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 2018. 1. 30. 오전 11:25) 
2018-01-30 17:18:53,676 [ 222972]   INFO - ij.compiler.impl.CompileDriver - COMPILATION STARTED (BUILD PROCESS) 
2018-01-30 17:18:53,735 [ 223031]  ERROR - CompilerConfigurationGenerator - MavenWebArtifactConfiguration already exists.

**Comment by kornilova-l** [comment]
@KyongSik-Yoon I was able to reproduce the error. So I suppose that path to your **home directory** (where .IntelliJIdea2017.3 dir is stored) **contains spaces** (or maybe some special characters)
I used wrong way to create a path to directory that contains static files :( it will be fixed in next release.
I will close the issue, but If your home directory path does not contain spaces and any special characters, please, leave a comment here

**Comment by KyongSik-Yoon** [comment]
Ok. I will check soon. Please wait to close until check.

**Comment by KyongSik-Yoon** [comment]
@kornilova-l I checked my IntelliJ home directory.
I didn't configure home. So I found IntelliJ home directory on my machine.
/Users/sam/Library/Preferences/IntelliJIdea2017.3

**Comment by KyongSik-Yoon** [comment]
How is being this issue going?
I think this issue caused by my environment. (Mac OS)
Is possible to fixed?

**Comment by kornilova-l** [comment]
@KyongSik-Yoon, hi,
Yes, maybe, back then I tried to install Mac OS on virtual machine but I failed because of low disk space. 2 weeks ago I bought new ssd but I was distracted by work and studying. Your reminder gives me motivation to try again :)

**Comment by KyongSik-Yoon** [comment]
Thank you. I always wish use your plugin on my environment.

**Comment by kornilova-l** [comment]
@KyongSik-Yoon I found out what was the problem. It indeed was caused by space character in path. Here is the thing: plugin files are stored in `~/Library/Application Support/IdeaIC2017.3/FlamegraphProfiler/...` directory, as you can see `Application Support` dir contains space char.
I reproduced the error with plugin version 0.7. Current version 0.8 works fine
So now you can install latest version from JetBrains plugins repository and it should work

**Comment by KyongSik-Yoon** [comment]
Wow thanks. It’s nice news. I will check and leave the feedback soon.

**Comment by KyongSik-Yoon** [comment]
@kornilova-l Finally I can see a result without errors. Thanks your effort.
Additionally I found other issue for profile configuration so I'll create new issue.
Thank you again.
