### ISSUE TITLE
Exception occurred when all of profile target setting to * (class, method, parameter)

### ISSUE THREAD

**Issue by KyongSik-Yoon** [kornilova-l/flamegraph-visualizer#8]
@kornilova-l  If configured all of include setting's value is * exception occurred and process to suspended. (cannot terminate so only possible by kill -3)
I didn't saw before this kind of error.
This exception threw during execute JUnit test.

Output file: /Users/sam/Library/Caches/IntelliJIdea2017.3/flamegraph-profiler/log/com.jennifersoft.aries.pom/ActiveServiceOriginCountMetricsCollectorSpec-2018-03-13-16_46_35.ser
Configuration:
Including patterns: 
	*.*(*)Exception in thread "logging thread" java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/github/kornilova_l/libs/com/google/protobuf/InvalidProtocolBufferException"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.github.kornilova_l.flamegraph.javaagent.logger.event_data_storage.MethodEventData.getEvents(MethodEventData.java:63)
	at com.github.kornilova_l.flamegraph.javaagent.logger.Logger.logEvents(Logger.java:84)
	at com.github.kornilova_l.flamegraph.javaagent.logger.Logger.run(Logger.java:62)
	at java.lang.Thread.run(Thread.java:748)

I add exclude setting all of your plugin classes to prevent duplicated loading. 
-> class = com.github.kornilova* method = * parameter = *
At the result, everything is ok.

I recommend to list up all classes of your plugin and prevent to visit.

**Comment by kornilova-l** [comment]
@KyongSik-Yoon, thanks for submitting issue!
There was a bug in `isClassOfAgent` method, it did not include protobuf runtime library into classes of agent. It will be fixed in next release

**Comment by KyongSik-Yoon** [comment]
@kornilova-l Great. I close this issue.
